name: Dependencies verification

on:
  push:
    branches:
      - 'dependabot/gradle/**'

  workflow_dispatch:

jobs:
  locksAndVerificationData:
    name: Update lock file & verification metadata
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Setup Java
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb

      - name: Run gradle command
        run: ./gradlew dependencies 
          androidApp:dependencies 
          desktopApp:dependencies 
          shared:dependencies 
          --write-locks 
          --write-verification-metadata sha256,pgp 
          --export-keys

      - name: Configure git for commit
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"

      - name: Commit
        run: |
          git add gradle/**
          git add **/*.lockfile
          git diff-index --cached --quiet HEAD -- || git commit -m "Updated lockfile & verification metadata"

      - name: Push
        run: git push